# frozen_string_literal: true

require "cmdx"
require "rspec"

require_relative "rspec/helpers"

require_relative "rspec/matchers/be_complete"
require_relative "rspec/matchers/be_deprecated"
require_relative "rspec/matchers/be_interrupted"
require_relative "rspec/matchers/be_ko"
require_relative "rspec/matchers/be_ok"
require_relative "rspec/matchers/be_successful"
require_relative "rspec/matchers/have_been_retried"
require_relative "rspec/matchers/have_been_rolled_back"
require_relative "rspec/matchers/have_callback"
require_relative "rspec/matchers/have_chain_root"
require_relative "rspec/matchers/have_chain_size"
require_relative "rspec/matchers/have_duration"
require_relative "rspec/matchers/have_empty_context"
require_relative "rspec/matchers/have_empty_metadata"
require_relative "rspec/matchers/have_errors_on"
require_relative "rspec/matchers/have_failed"
require_relative "rspec/matchers/have_input"
require_relative "rspec/matchers/have_matching_context"
require_relative "rspec/matchers/have_matching_metadata"
require_relative "rspec/matchers/have_middleware"
require_relative "rspec/matchers/have_no_errors"
require_relative "rspec/matchers/have_output"
require_relative "rspec/matchers/have_pipeline_tasks"
require_relative "rspec/matchers/have_retry_on"
require_relative "rspec/matchers/have_skipped"
require_relative "rspec/matchers/have_tag"
require_relative "rspec/matchers/raise_cmdx_fault"
